{% set name = "onnxconverter-common" %}
{% set version = "1.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/microsoft/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: d3b468b19e4318983635e4cda95985c11a554c2e5704240c513ff0c7d9e361bf

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - numpy
    - protobuf
    - onnx

test:
  imports:
    - onnxconverter_common
    
about:
  home: https://github.com/microsoft/onnxconverter-common
  license: MIT
  license_file: LICENSE
  summary: 'Common utilities for ONNX converters.'
  description: |
    The onnxconverter-common package provides common functions and utilities for use in converters from various AI frameworks to ONNX.
    It also enables the different converters to work together to convert a model from mixed frameworks, like a scikit-learn pipeline embedding a xgboost model.

extra:
  recipe-maintainers:
    - DavidKatz-il
    - sephib
